/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.pallasathenagroup.querydsl.java-conventions")
}

dependencies {
    implementation(projects.querydslExtApi)
    implementation(libs.jackson.databind)
    implementation(libs.hibernate.core)
    implementation(libs.hypersistence)
}

description = "querydsl-ext-impl"
