/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.pallasathenagroup.querydsl.java-conventions")
}

dependencies {
    implementation(projects.querydslExtApi)
    implementation(libs.querydsl.apt) {
        artifact {
            classifier = "jakarta"
        }
    }
    implementation(libs.guava)
    implementation(libs.hibernate.core)
    implementation(libs.javax.money)
    testImplementation("org.jadira.usertype:usertype.spi:6.0.1.GA")
    testImplementation("org.jadira.usertype:usertype.core:6.0.1.GA")
    compileOnly(libs.jackson.databind)
}

description = "querydsl-ext-apt"
