/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.pallasathenagroup.querydsl.java-conventions")
}

dependencies {
    implementation(libs.hibernate.core)
    implementation(libs.hypersistence)
    implementation(libs.jackson.databind)
    implementation(libs.guava)
    implementation(libs.querydsl.jpa) {
        artifact {
            classifier = "jakarta"
        }
    }
    compileOnly("org.jetbrains:annotations:21.0.1")
    compileOnly(libs.javax.money)
    compileOnly(libs.postgresql)
}

description = "querydsl-ext-api"
